### ISSUE TITLE
What if you need to update the theme? 

### ISSUE THREAD

**Issue by mmm8955405** [delucis/astro-netlify-cms#4]
Directly reference the layout and code of the theme. What if you need to update the theme? It's a bigger problem for you to switch themes. Do you consider providing module references

**Comment by delucis** [comment]
Hey there! This is an experimental example, so a good place for us to find good solutions.

Do you mean what if you want to change the layout for a specific blog post or what if you want to customise the blog more generally?

**Comment by mmm8955405** [comment]
> Do you mean what if you want to change the layout for a specific blog post or what if you want to customise the blog more generally?

yes. According to the current design method, I find it difficult to update the theme and define the theme myself. Jekyll's method of changing themes seems relatively simple. But this is not within the scope of the bug. Let me turn it off

**Comment by delucis** [comment]
Ah, ok. Yes, this seems more like an issue with understanding how to change Astro themes more generally rather than with this example (which is focused on integrating with Netlify CMS).

Currently you'd need to dive into components and layouts and modify them yourself. I am experimenting with Astro's new integrations API, which once stable should allow you to include a Netlify CMS integration in your Astro configuration file and not need to modify other files in a project. When that's ready it would be easier to drop Netlify CMS support into a project.

**Comment by mmm8955405** [comment]
> Ah, ok. Yes, this seems more like an issue with understanding how to change Astro themes more generally rather than with this example (which is focused on integrating with Netlify CMS).
> 
> Currently you'd need to dive into components and layouts and modify them yourself. I am experimenting with Astro's new integrations API, which once stable should allow you to include a Netlify CMS integration in your Astro configuration file and not need to modify other files in a project. When that's ready it would be easier to drop Netlify CMS support into a project.

That's great. I hope this new API function will come out as soon as possible. Why doesn't Astro implement a CMS by itself, similar to ghost admin.

**Comment by delucis** [comment]
I see Astro’s strength more as a templating language to generate sites, so people will want to use it with loads of different CMS products, so Netlify CMS is one option but [headless services](https://jamstack.org/headless-cms/) like Storyblok, Sanity, Tina, Contentful, Strapi etc. or even Wordpress via its REST API are all possibilities.
